include $(TOPDIR)/rules.mk

LUCI_TITLE:=Solve2Surf Captive Portal Configuration
LUCI_DEPENDS:=+solve2surf +luci-base
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-solve2surf
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature